docs(contributors guide): Updated contributors guide
akv-platform/setup-go pull request #5
Opened 2022-07-14 12:35 UTC by e-korolevskii

**Description:**
Describe your changes.

**Related issue:**
Add link to the related issue.

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-07-14 14:06 UTC, IvanZosimov requested changes

2022-07-14 14:28 UTC, e-korolevskii commented on docs/contributors.md
> +**How to contribute:**
I think the answer to this will be contained in the discussion below, everything will depend on the level of explanation to which we aspire.

2022-07-14 14:30 UTC, e-korolevskii commented on docs/contributors.md
> + * [Contribute Code :computer:](#contribute-code)
I think they can easily use navigation, in any case, the process of editing documentation and code has several small differences and one critical one - the presence of tests. So I decided to highlight it separately.

2022-07-15 09:22 UTC, marko-zivic-93 approved these changes

2022-07-15 09:22 UTC, marko-zivic-93 commented on docs/contributors.md
> + - As much as possible, try to refer to past issues with accepted answers. Link to them from your replies with the #123 format
Just reverse the order:
"Try to refer to past issues with accepted answers as much as possible."

2022-07-18 09:44 UTC, dmitry-shibanov commented on docs/contributors.md
> +- Clone the repository to your local machine
I do not think we should be so detailed in this case because customers can't in general make a pull request without forking our repository so the only way is to make a fork. Besides, clone repository step is obvious step to make it. Moreover, some customers can make changes using codespace

2022-07-22 09:50 UTC, panticmilos approved these changes

2022-07-22 13:16 UTC, vsafonkin approved these changes

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +The main difference between code contributions and documentation contributions is that contributing code requires the inclusion of relevant tests for the code being added or changed. Contributions wi
```suggestion
The main difference between code contributions and documentation contributions is that contributing code requires the inclusion of relevant tests for the code being added or changed.
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- If your pull request is connected to an open issue, add a line in your pull request's description that says Fixes: #123, where #123 is the number of the issue you're fixing.
```suggestion
- If your pull request is connected to an open issue, please, leave a link to this issue in the `Related issue:` section
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- To compile source code to `javascript` we use [NCC](https://github.com/vercel/ncc). **It is very important to run the `build` script after making changes**, otherwise your changes will not get into
If I been really over-picky, I would say:  
```suggestion
- To transpile source code to `javascript` we use [NCC](https://github.com/vercel/ncc). **It is very important to run the `build` script after making changes**, otherwise your changes will not get into the final `javascript` build
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +Adding or changing tests is an integral part of making a change to the code. The tests are located in the `__tests__` folder and cover most of the functionality of the repository.
We forgot about the e2e test location.

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- CI will start automatically with some checks. Wait until the end of the execution and make sure that all checks passed successfully. If some checks fail, you can make changes to your code
```suggestion
- CI will start automatically with some checks. Wait until the end of the execution and make sure that all checks passed successfully. If some checks fail, you can open them one by one, try to find the reason for failing and make changes to your code to resolve the problem
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- One or more maintainers will use GitHub's review feature to review your pull request
```suggestion
- Maintainers will review your pull request
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- If the maintainer asks for any changes, edit your changes, push, and ask for another review
```suggestion
- If a maintainer requests changes, first of all, try to think about his request critically and only after that implement and request another review
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- If your PR gets accepted, it will be merged into the latest branch soon after. Your contribution will be distributed to the masses next time the maintainers tag a release
```suggestion
- If your PR gets accepted, it will soon be merged into the main branch. But your contribution will take effect only after the release of a new version of the action
> Sometimes maintainers reject pull requests and that's ok! Usually, along with rejection, we supply the reason for it. Nonetheless, we still really appreciate you taking the time to do it, and we don't take that lightly :heart:
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- Try to refer to past issues with accepted answers as much as possible. Link to them from your replies with the #123 format
I suggest deleting the part with #123 format here and above in the doc because when you paste the link to a GH issue in the comment it's automatically converted to this format.
```suggestion
- Try to refer to past issues with accepted answers as much as possible. Link to them from your replies
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- Be kind and patient with users -- often, folks who have run into confusing things might be upset or impatient. This is ok. Try to understand where they're coming from, and if you're too uncomfortab
```suggestion
- Be kind and patient with users. Often, folks who have run into confusing things might be upset or impatient. This is natural. If you feel uncomfortable in conversation with them, it's better to stay away or withdraw from the issue.

 > If some user is violating our code of conduct [standards](https://github.com/actions/setup-go/blob/main/CODE_OF_CONDUCT.md#our-standards), refer to the [Enforcement](https://github.com/actions/setup-go/blob/main/CODE_OF_CONDUCT.md#enforcement) section of the Code of Conduct to resolve the conflict
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +Another great way to contribute is pull request reviews. Please, be extra kind: people who submit code/doc contributions are putting themselves in a pretty vulnerable position, and have put time and
```suggestion
Another great way to contribute is pull request reviews. Please, be extra kind: people who submit code/doc contributions are putting themselves in a pretty vulnerable position, and have put time and care into what they've done (even if that's not obvious to you!) Please, always respond with respect, and be understanding, but don't feel like you need to sacrifice your standards for their sake, either.
```

2022-07-25 09:52 UTC, IvanZosimov commented on docs/contributors.md
> +- Review changes using the GitHub functionality. You can ask a clarifying question, point out an error or suggest an alternative. (Note: You may ask for minor changes ("nitpicks"), but consider wheth
```suggestion
- Review changes using the GitHub functionality. You can ask a clarifying question, point out an error or suggest an alternative. 
> Note: You may ask for minor changes - "nitpicks", but consider whether they are real blockers to merging or not
```

2022-07-26 10:45 UTC, IvanZosimov approved these changes

2022-07-26 10:50 UTC, merged